# Generated by Django 6.0.4 on 2026-04-21 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('slot', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('equipment', 'Equipment')], default='primary', max_length=16)),
                ('base_damage', models.PositiveSmallIntegerField()),
                ('magazine_capacity', models.PositiveSmallIntegerField(default=30)),
                ('reserve_ammo', models.PositiveSmallIntegerField(default=90)),
                ('rounds_per_minute', models.PositiveSmallIntegerField(default=600)),
                ('reload_time_ms', models.PositiveIntegerField(default=2500)),
                ('effective_range_meters', models.DecimalField(decimal_places=2, default=25, max_digits=5)),
                ('pellets_per_shot', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['slot', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BombSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16)),
                ('label', models.CharField(max_length=32)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bomb_sites', to='gameplay.arena')),
            ],
            options={
                'ordering': ['arena__name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('bomb_defusal', 'Bomb Defusal')], default='bomb_defusal', max_length=32)),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('live', 'Live'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='staged', max_length=16)),
                ('team_size', models.PositiveSmallIntegerField(default=5)),
                ('round_time_limit_seconds', models.PositiveSmallIntegerField(default=115)),
                ('bomb_timer_seconds', models.PositiveSmallIntegerField(default=40)),
                ('current_round_number', models.PositiveSmallIntegerField(default=0)),
                ('winning_side', models.CharField(blank=True, choices=[('T', 'Terrorists'), ('CT', 'Counter-Terrorists')], max_length=2, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('arena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='gameplay.arena')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('side', models.CharField(choices=[('T', 'Terrorists'), ('CT', 'Counter-Terrorists')], max_length=2)),
                ('display_name', models.CharField(max_length=64)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='gameplay.match')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_entries', to='gameplay.team')),
            ],
            options={
                'ordering': ['match_id', 'side'],
            },
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_identifier', models.CharField(blank=True, max_length=64)),
                ('gun_identifier', models.CharField(blank=True, max_length=64)),
                ('vest_identifier', models.CharField(blank=True, max_length=64)),
                ('is_connected', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='gameplay.match')),
                ('match_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='gameplay.matchteam')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_entries', to='gameplay.player')),
                ('selected_weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_players', to='gameplay.weapon')),
            ],
            options={
                'ordering': ['match_id', 'player__display_name'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('live', 'Live'), ('complete', 'Complete')], default='preparing', max_length=16)),
                ('winning_side', models.CharField(blank=True, choices=[('T', 'Terrorists'), ('CT', 'Counter-Terrorists')], max_length=2, null=True)),
                ('win_reason', models.CharField(blank=True, choices=[('elimination', 'Elimination'), ('bomb_defused', 'Bomb Defused'), ('bomb_detonated', 'Bomb Detonated'), ('time_expired', 'Time Expired'), ('forfeit', 'Forfeit')], max_length=32, null=True)),
                ('bomb_planted_at', models.DateTimeField(blank=True, null=True)),
                ('bomb_defused_at', models.DateTimeField(blank=True, null=True)),
                ('bomb_detonated_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('bomb_defused_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bomb_defuses', to='gameplay.matchplayer')),
                ('bomb_planted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bomb_plants', to='gameplay.matchplayer')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='gameplay.match')),
                ('planted_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planted_rounds', to='gameplay.bombsite')),
            ],
            options={
                'ordering': ['match_id', 'number'],
            },
        ),
        migrations.CreateModel(
            name='BombEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('occurred_at', models.DateTimeField()),
                ('kind', models.CharField(choices=[('plant_started', 'Plant Started'), ('planted', 'Planted'), ('defuse_started', 'Defuse Started'), ('defuse_cancelled', 'Defuse Cancelled'), ('defused', 'Defused'), ('detonated', 'Detonated')], max_length=32)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bomb_events', to='gameplay.bombsite')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bomb_events', to='gameplay.matchplayer')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bomb_events', to='gameplay.round')),
            ],
            options={
                'ordering': ['round_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='gameplay.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='gameplay.team')),
            ],
        ),
        migrations.CreateModel(
            name='RoundPlayerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starting_health', models.PositiveSmallIntegerField(default=100)),
                ('current_health', models.PositiveSmallIntegerField(default=100)),
                ('alive', models.BooleanField(default=True)),
                ('deaths', models.PositiveSmallIntegerField(default=0)),
                ('match_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_states', to='gameplay.matchplayer')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_states', to='gameplay.round')),
                ('equipped_weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_in_round_states', to='gameplay.weapon')),
            ],
            options={
                'ordering': ['round_id', 'match_player_id'],
            },
        ),
        migrations.CreateModel(
            name='CombatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('occurred_at', models.DateTimeField()),
                ('damage', models.PositiveSmallIntegerField()),
                ('victim_health_after', models.PositiveSmallIntegerField()),
                ('was_lethal', models.BooleanField(default=False)),
                ('attacker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_dealt_events', to='gameplay.matchplayer')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_taken_events', to='gameplay.matchplayer')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_events', to='gameplay.round')),
                ('weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combat_events', to='gameplay.weapon')),
            ],
            options={
                'ordering': ['round_id', 'sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='bombsite',
            constraint=models.UniqueConstraint(fields=('arena', 'code'), name='unique_bomb_site_per_arena'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('match', 'number'), name='unique_round_number_per_match'),
        ),
        migrations.AddConstraint(
            model_name='bombevent',
            constraint=models.UniqueConstraint(fields=('round', 'sequence'), name='unique_bomb_sequence_per_round'),
        ),
        migrations.AddConstraint(
            model_name='matchteam',
            constraint=models.UniqueConstraint(fields=('match', 'side'), name='unique_match_side'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(fields=('team', 'player'), name='unique_team_membership'),
        ),
        migrations.AddConstraint(
            model_name='roundplayerstate',
            constraint=models.UniqueConstraint(fields=('round', 'match_player'), name='unique_round_state_per_player'),
        ),
        migrations.AddConstraint(
            model_name='matchplayer',
            constraint=models.UniqueConstraint(fields=('match', 'player'), name='unique_player_per_match'),
        ),
        migrations.AddConstraint(
            model_name='combatevent',
            constraint=models.UniqueConstraint(fields=('round', 'sequence'), name='unique_combat_sequence_per_round'),
        ),
    ]
