# Generated by Django 6.0.4 on 2026-04-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arena',
            options={'ordering': ['name'], 'verbose_name': 'arena', 'verbose_name_plural': 'arenas'},
        ),
        migrations.AlterModelOptions(
            name='bombevent',
            options={'ordering': ['round_id', 'sequence'], 'verbose_name': 'bomb event', 'verbose_name_plural': 'bomb events'},
        ),
        migrations.AlterModelOptions(
            name='bombsite',
            options={'ordering': ['arena__name', 'code'], 'verbose_name': 'bomb site', 'verbose_name_plural': 'bomb sites'},
        ),
        migrations.AlterModelOptions(
            name='combatevent',
            options={'ordering': ['round_id', 'sequence'], 'verbose_name': 'combat event', 'verbose_name_plural': 'combat events'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-created_at'], 'verbose_name': 'match', 'verbose_name_plural': 'matches'},
        ),
        migrations.AlterModelOptions(
            name='matchplayer',
            options={'ordering': ['match_id', 'player__display_name'], 'verbose_name': 'match player', 'verbose_name_plural': 'match players'},
        ),
        migrations.AlterModelOptions(
            name='matchteam',
            options={'ordering': ['match_id', 'side'], 'verbose_name': 'match team', 'verbose_name_plural': 'match teams'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['display_name'], 'verbose_name': 'player', 'verbose_name_plural': 'players'},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['match_id', 'number'], 'verbose_name': 'round', 'verbose_name_plural': 'rounds'},
        ),
        migrations.AlterModelOptions(
            name='roundplayerstate',
            options={'ordering': ['round_id', 'match_player_id'], 'verbose_name': 'round player state', 'verbose_name_plural': 'round player states'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
        migrations.AlterModelOptions(
            name='teammembership',
            options={'verbose_name': 'team membership', 'verbose_name_plural': 'team memberships'},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ['slot', 'name'], 'verbose_name': 'weapon', 'verbose_name_plural': 'weapons'},
        ),
    ]
