# Generated by Django 6.0.4 on 2026-04-21 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_alter_arena_options_alter_bombevent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('occurred_at', models.DateTimeField()),
                ('pulse_identifier', models.CharField(db_index=True, max_length=64)),
                ('shot_identifier', models.CharField(blank=True, db_index=True, max_length=64)),
                ('reporting_device_identifier', models.CharField(blank=True, max_length=64)),
                ('source_device_identifier', models.CharField(blank=True, max_length=64)),
                ('sensor_code', models.CharField(blank=True, max_length=32)),
                ('sensor_zone', models.CharField(choices=[('head', 'Head'), ('torso', 'Torso'), ('back', 'Back'), ('left_arm', 'Left Arm'), ('right_arm', 'Right Arm'), ('left_leg', 'Left Leg'), ('right_leg', 'Right Leg'), ('gear', 'Gear'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('signal_strength', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resolution_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected_duplicate', 'Rejected Duplicate'), ('rejected_friendly_fire', 'Rejected Friendly Fire'), ('rejected_round_inactive', 'Rejected Round Inactive'), ('rejected_target_dead', 'Rejected Target Dead'), ('rejected_unknown_source', 'Rejected Unknown Source'), ('rejected_invalid_pulse', 'Rejected Invalid Pulse')], default='pending', max_length=32)),
                ('resolution_notes', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('attacker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hit_reports_sent', to='gameplay.matchplayer')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hit_reports', to='gameplay.round')),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hit_reports_received', to='gameplay.matchplayer')),
                ('weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hit_reports', to='gameplay.weapon')),
            ],
            options={
                'verbose_name': 'hit report',
                'verbose_name_plural': 'hit reports',
                'ordering': ['round_id', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='combatevent',
            name='hit_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combat_event', to='gameplay.hitreport'),
        ),
        migrations.AddIndex(
            model_name='combatevent',
            index=models.Index(fields=['round', 'occurred_at'], name='combatevent_round_time_idx'),
        ),
        migrations.AddIndex(
            model_name='combatevent',
            index=models.Index(fields=['victim', 'occurred_at'], name='combatevent_victim_time_idx'),
        ),
        migrations.AddIndex(
            model_name='combatevent',
            index=models.Index(fields=['attacker', 'occurred_at'], name='combatevent_attacker_time_idx'),
        ),
        migrations.AddIndex(
            model_name='combatevent',
            index=models.Index(fields=['weapon', 'occurred_at'], name='combatevent_weapon_time_idx'),
        ),
        migrations.AddIndex(
            model_name='hitreport',
            index=models.Index(fields=['round', 'occurred_at'], name='hitreport_round_time_idx'),
        ),
        migrations.AddIndex(
            model_name='hitreport',
            index=models.Index(fields=['victim', 'occurred_at'], name='hitreport_victim_time_idx'),
        ),
        migrations.AddIndex(
            model_name='hitreport',
            index=models.Index(fields=['attacker', 'occurred_at'], name='hitreport_attacker_time_idx'),
        ),
        migrations.AddIndex(
            model_name='hitreport',
            index=models.Index(fields=['resolution_status'], name='hitreport_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='hitreport',
            constraint=models.UniqueConstraint(fields=('round', 'sequence'), name='unique_hit_sequence_per_round'),
        ),
    ]
