# Generated by Django 6.0.4 on 2026-04-21 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_hitreport_combatevent_hit_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundplayerstate',
            name='current_magazine_ammo',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roundplayerstate',
            name='current_reserve_ammo',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roundplayerstate',
            name='reload_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roundplayerstate',
            name='shots_fired',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FireEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('occurred_at', models.DateTimeField()),
                ('trigger_identifier', models.CharField(db_index=True, max_length=64)),
                ('burst_size', models.PositiveSmallIntegerField(default=1)),
                ('reporting_device_identifier', models.CharField(blank=True, max_length=64)),
                ('source_device_identifier', models.CharField(blank=True, max_length=64)),
                ('magazine_ammo_before', models.PositiveSmallIntegerField(default=0)),
                ('magazine_ammo_after', models.PositiveSmallIntegerField(default=0)),
                ('reserve_ammo_before', models.PositiveSmallIntegerField(default=0)),
                ('reserve_ammo_after', models.PositiveSmallIntegerField(default=0)),
                ('empty_trigger', models.BooleanField(default=False)),
                ('requires_reload', models.BooleanField(default=False)),
                ('resolution_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected_duplicate', 'Rejected Duplicate'), ('rejected_round_inactive', 'Rejected Round Inactive'), ('rejected_player_dead', 'Rejected Player Dead'), ('rejected_unknown_source', 'Rejected Unknown Source'), ('rejected_no_ammo', 'Rejected No Ammo'), ('rejected_invalid_payload', 'Rejected Invalid Payload')], default='pending', max_length=32)),
                ('resolution_notes', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_events', to='gameplay.round')),
                ('shooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_events', to='gameplay.matchplayer')),
                ('weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fire_events', to='gameplay.weapon')),
            ],
            options={
                'verbose_name': 'fire event',
                'verbose_name_plural': 'fire events',
                'ordering': ['round_id', 'sequence'],
                'indexes': [models.Index(fields=['round', 'occurred_at'], name='fireevent_round_time_idx'), models.Index(fields=['shooter', 'occurred_at'], name='fireevent_shooter_time_idx'), models.Index(fields=['weapon', 'occurred_at'], name='fireevent_weapon_time_idx'), models.Index(fields=['resolution_status'], name='fireevent_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('round', 'sequence'), name='unique_fire_sequence_per_round')],
            },
        ),
    ]
